#+title: capnp-janet
#+options: toc:nil num:nil title:nil

#+begin_export rst
capnp-janet
===========

Native Cap'n Proto runtime for `Janet <https://janet-lang.org>`_, plus a
C library embedders can link without the Janet VM.
#+end_export

Sibling runtimes: [[https://c-capnproto.rgoswami.me][c-capnproto]] and
[[https://capnp-fortran.rgoswami.me][capnp-fortran]]. Status: =0.2.0-dev=.
AddressBook encode matches official =capnp encode= when fields are set
in schema order.

* Install (shortest path)

#+begin_src console
$ git clone https://github.com/HaoZeke/capnp-janet.git
$ cd capnp-janet
$ pixi install && pixi run configure && pixi run build && pixi run test
#+end_src

* First message (Janet)

#+begin_src janet
(import capnp)

(def buf (capnp/build-demo 42 "hello" ["a" "bb"]))
(def msg (capnp/message-from-buffer buf))
(def root (capnp/root msg))
(print (capnp/get-u32 root 0))        # 42
(print (capnp/get-text root 0))       # hello
(def items (capnp/getp root 1))
(print (capnp/list-get-text items 1)) # bb
#+end_src

C embed (no Janet VM):

#+begin_src c
#include <capnp-janet/capnp_message.h>

capnp_message_t msg;
capnp_message_view_flat(&msg, bytes, len);
capnp_ptr_t root;
capnp_root(&msg, &root);
const char *s; size_t n;
capnp_get_text(&root, 0, &s, &n);
#+end_src

The [[file:tutorial.org][tutorial]] walks AddressBook encode and the
embed register path.

* Documentation map

#+begin_export rst
.. grid:: 1 2 2 2
   :gutter: 2

   .. grid-item-card:: Install
      :link: install
      :link-type: doc

      pixi, Meson, C embed, Janet module.

   .. grid-item-card:: Tutorial
      :link: tutorial
      :link-type: doc

      First buffer, AddressBook, ``capnp_janet_register``.

   .. grid-item-card:: Architecture
      :link: architecture
      :link-type: doc

      C layers, zero-copy views, compiled ``.jimage`` packs.

   .. grid-item-card:: Wire
      :link: wire
      :link-type: doc

      Packed, canonical, list evolution.

.. toctree::
   :maxdepth: 1
   :hidden:

   install
   tutorial
   architecture
   wire
#+end_export
